#!/usr/bin/env python3
"""
gen_silu_lut.py — Generate SiLU activation lookup table for Posit16
Produces silu_lut.hex for $readmemh loading in yolo_silu_lut.sv

SiLU(x) = x * sigmoid(x) = x / (1 + exp(-x))

The LUT maps 1024 Posit16 input values to their SiLU outputs.
Index mapping: addr = posit16[14:5] (10-bit index from magnitude bits)
"""

import math
import os
import sys

# Add parent for Posit16 class
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_golden_vectors import Posit16, POSIT_WIDTH


def silu(x: float) -> float:
    """Compute SiLU(x) = x * sigmoid(x)."""
    if x > 20:
        return x  # sigmoid ≈ 1
    elif x < -20:
        return 0.0  # sigmoid ≈ 0
    return x / (1.0 + math.exp(-x))


def generate_silu_lut(output_dir: str = "."):
    """Generate 1024-entry SiLU LUT in Posit16 format."""
    LUT_DEPTH = 1024
    filepath = os.path.join(output_dir, "silu_lut.hex")

    print(f"Generating SiLU LUT ({LUT_DEPTH} entries) → {filepath}")

    entries = []
    for addr in range(LUT_DEPTH):
        # Reconstruct Posit16 input from address
        # addr = posit16[14:5], so posit16 ≈ addr << 5
        # We compute for both positive range (the LUT covers unsigned magnitude)
        posit_bits = addr << 5  # place in upper bits

        # Decode to float
        input_val = Posit16.decode(posit_bits)

        if math.isnan(input_val):
            output_bits = Posit16.NAR
        elif abs(input_val) < 1e-30:
            output_bits = Posit16.ZERO
        else:
            output_val = silu(input_val)
            output_bits = Posit16.encode(output_val)

        entries.append(output_bits)

    # Write hex file
    with open(filepath, 'w') as f:
        f.write("// SiLU LUT: 1024 entries, Posit<16,1>\n")
        f.write("// Generated by gen_silu_lut.py\n")
        f.write(f"// Index mapping: addr = posit16_input[14:5]\n")
        for i, val in enumerate(entries):
            f.write(f"{val:04X}\n")

    # Also write a human-readable CSV for verification
    csv_filepath = os.path.join(output_dir, "silu_lut_debug.csv")
    with open(csv_filepath, 'w') as f:
        f.write("addr,input_hex,input_value,output_hex,output_value\n")
        for addr in range(LUT_DEPTH):
            posit_in = addr << 5
            val_in = Posit16.decode(posit_in)
            val_out = Posit16.decode(entries[addr])
            f.write(f"{addr},{posit_in:04X},{val_in:.6f},{entries[addr]:04X},{val_out:.6f}\n")

    print(f"  Also wrote debug CSV: {csv_filepath}")
    print(f"  Entry 0 (zero):  0x{entries[0]:04X} = {Posit16.decode(entries[0])}")
    print(f"  Entry 128 (~1.0): 0x{entries[128]:04X} = {Posit16.decode(entries[128]):.4f}")

    return entries


if __name__ == "__main__":
    output_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    generate_silu_lut(output_dir)
    print("✓ SiLU LUT generated")
